name = "muxile"
main = "src/muxile.mjs"
compatibility_date = "2024-01-01"

# Add your account ID here
account_id = ""

rules = [
  { type = "Data", globs = ["**/*.html"] }
]

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
